-- FOR ADVANCE SQL
SELECT * FROM HR.EMPLOYEES;

-- FOR MAXIMUM SALARY
SELECT * FROM HR.EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

-- FOR TOP THREE HIGHEST EARNING EMPLOYEES IN THE COMPANY
SELECT * FROM HR.EMPLOYEES WHERE ROWNUM <= 3 ORDER BY SALARY DESC;
-- OR USING SUBQUERY ABOVE QUERY COULD BE WRITTEN
SELECT * FROM (SELECT * FROM HR.EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 3;