-- FOR ADVANCE SQL
SELECT * FROM HR.EMPLOYEES;

-- FOR MAXIMUM SALARY
SELECT * FROM HR.EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

-- FOR TOP THREE HIGHEST EARNING EMPLOYEES IN THE COMPANY
SELECT * FROM HR.EMPLOYEES WHERE ROWNUM <= 3 ORDER BY SALARY DESC;
-- OR USING SUBQUERY ABOVE QUERY COULD BE WRITTEN
SELECT * FROM (SELECT * FROM HR.EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 3;

SELECT * FROM DUAL;

-- SINGLE VALUE SUBQUERY
SELECT * FROM HR.EMPLOYEES WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

-- USING MULTIVALUE SUBQUERY
SELECT * FROM HR.DEPARTMENTS;
-- FIND ALL THE DEPARTMENT ID FROM THE DEPARTMENTS TABLE WHER THE LOCATION OF THE EMPLOYEES IS 1700
SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE LOCATION_ID = 1700;

-- FIND ALL THE EMPLOYEES FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROMEMPLOYEES AND DEPARTMENTS TABLE WHERE THE SUBQUERY RETURN THE MULTIPLE VALUES
SELECT E.FIRST_NAME,E.LAST_NAME,E.DEPARTMENT_ID FROM HR.EMPLOYEES E WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE LOCATION_ID = 1700);

-- WE CAN USE NOT IN INSTEAD OF IN KEYWORD
SELECT E.FIRST_NAME,E.LAST_NAME,E.DEPARTMENT_ID FROM HR.EMPLOYEES E WHERE E.DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE LOCATION_ID = 1700);

-- CORRELATED QUERY
-- FIND THE NUMBER LIST OF EMPLOYEE HAVING THE HIGHER SALARY AS COMPARE TO THE AVG SALARY OF THE EMPLOYEES
SELECT EMPLOYEE_ID,SALARY,DEPARTMENT_ID FROM HR.EMPLOYEES E WHERE SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES E1 WHERE E.DEPARTMENT_ID = E1.DEPARTMENT_ID);

-- USING MULTIPLE COLUMN SUBQUERY
SELECT * FROM HR.JOBS;
SELECT MIN_SALARY,JOB_ID FROM HR.JOBS;
-- FIND THE LIST OF EMPLOYEES HAVING THE MINSALARY AND THE JOB_ID 
-- HERE WE ARE PASSING TWO COLUMN FROM THE SUBQUERY TO THE MAIN QUERY

SELECT * FROM HR.EMPLOYEES WHERE (SALARY,JOB_ID) IN (SELECT MIN_SALARY,JOB_ID FROM HR.JOBS);

-- USING INLINE VIEW
-- FIND THE COUNT OF THE EMP WHICH IS ASSIGNED TO THE DEPARTMENT_ID
SELECT DEPARTMENT_ID,COUNT(*) EMP_COUNT FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT * FROM (SELECT DEPARTMENT_ID,COUNT(*) EMP_COUNT FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID) EMP
JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID;

SELECT * FROM HR.DEPARTMENTS;
SELECT * FROM (SELECT * FROM HR.EMPLOYEES WHERE COMMISSION_PCT IS  NULL ORDER BY SALARY DESC)
WHERE ROWNUM <=3;
